[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "blog_os.json"

#run in qemu
[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target.aarch64-unknown-none]
runner = "qemu-system-aarch64"
rustflags = [
    "-C",
    "link-args=-nostartfiles",
    "-C",
    "link-args=-nodefaultlibs",
    "-C",
    "link-args=-nostdlib",
]
